name: Build and Deploy to TKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
  TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
  TENCENT_CLOUD_PRODUCT_REGION: ${{ secrets.TENCENT_CLOUD_PRODUCT_REGION }}
  TECENT_CLOUD_ACCOUNT_ID: ${{ secrets.TECENT_CLOUD_ACCOUNT_ID }}
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE: webapp

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$REGISTRY_URL"/"$IMAGE":"$GITHUB_SHA" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push $REGISTRY_URL/$IMAGE:$GITHUB_SHA
