name: Build and Deploy to TKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
  TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
  TENCENT_CLOUD_ACCOUNT_ID: ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }}
  TKE_REGISTRY_PASSWORD: ${{ secrets.TKE_REGISTRY_PASSWORD }}
  TKE_IMAGE_URL: ${{ secrets.TKE_IMAGE_URL }}
  TKE_REGION: ${{ secrets.TKE_REGION }}
  TKE_CLUSTER_ID: ${{ secrets.TKE_CLUSTER_ID }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Build Docker image
      run: |        
        docker build -t "$TKE_IMAGE_URL":"$GITHUB_SHA" .

    - name: Login TKE Registry
      run: |
        docker login -u "$TENCENT_CLOUD_ACCOUNT_ID" -p "$TKE_REGISTRY_PASSWORD" "$TKE_IMAGE_URL"

    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push $TKE_IMAGE_URL:$GITHUB_SHA

    # Set TKE kubeconfig to ~/.kube/config
    - uses: mingshun/tke-cluster-credential-action@master
      with:
        secret_id: ${{ TENCENT_CLOUD_ACCOUNT_ID }}
        secret_key: ${{ TENCENT_CLOUD_SECRET_KEY }}
        tke_region: ${{ TKE_REGION }}
        cluster_id: ${{ TKE_CLUSTER_ID }}
    
    # Switch to TKE context
    - run: |
        kubectl config get-contexts
        kubectl config use-context "$TKE_CLUSTER_ID"-context-default
    
    - run: |
        kubectl get pods

