name: Build and Deploy to TKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
  TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
  TENCENT_CLOUD_PRODUCT_REGION: ${{ secrets.TENCENT_CLOUD_PRODUCT_REGION }}
  TECENT_CLOUD_ACCOUNT_ID: ${{ secrets.TECENT_CLOUD_ACCOUNT_ID }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE: ${{ secrets.IMAGE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$IMAGE":"$GITHUB_SHA" .
        
    # Login TKE Registry
    - run: |
        docker login -u "$TECENT_CLOUD_ACCOUNT_ID" -p "$REGISTRY_PASSWORD" "$IMAGE"

    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push $IMAGE:$GITHUB_SHA
