name: Build and Deploy to TKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  TENCENT_CLOUD_SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
  TENCENT_CLOUD_SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
  TENCENT_CLOUD_PRODUCT_REGION: ${{ secrets.TENCENT_CLOUD_PRODUCT_REGION }}
  TENCENT_CLOUD_ACCOUNT_ID: ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }}
  TKE_REGISTRY_PASSWORD: ${{ secrets.TKE_REGISTRY_PASSWORD }}
  TKE_IMAGE_URL: ${{ secrets.TKE_IMAGE_URL }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$TKE_IMAGE_URL":"$GITHUB_SHA" .
        
    # Login TKE Registry
    - run: |
        docker login -u "$TENCENT_CLOUD_ACCOUNT_ID" -p "$TKE_REGISTRY_PASSWORD" "$TKE_IMAGE_URL"

    # Push the Docker image to TKE Registry
    - name: Publish
      run: |
        docker push $TKE_IMAGE_URL:$GITHUB_SHA
